---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__(<p>__start__</p>)
	classifier(classifier)
	agent_tu_van(agent_tu_van)
	agent_dat_ve(agent_dat_ve)
	action_tu_van(action_tu_van)
	action_dat_ve(action_dat_ve)
	kiem_tra_dang_nhap(kiem_tra_dang_nhap)
	dang_nhap(dang_nhap)
	__end__(<p>__end__</p>)
	__start__ --> classifier;
	action_dat_ve --> agent_dat_ve;
	action_tu_van --> agent_tu_van;
	agent_dat_ve -. &nbsp;False&nbsp; .-> __end__;
	agent_dat_ve -. &nbsp;True&nbsp; .-> action_dat_ve;
	agent_tu_van -. &nbsp;False&nbsp; .-> __end__;
	agent_tu_van -. &nbsp;True&nbsp; .-> action_tu_van;
	classifier -. &nbsp;True&nbsp; .-> agent_tu_van;
	classifier -. &nbsp;False&nbsp; .-> dang_nhap;
	dang_nhap -. &nbsp;False&nbsp; .-> __end__;
	dang_nhap -. &nbsp;True&nbsp; .-> agent_dat_ve;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
